

####################################
server:
 port: 7000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dattabinit/udemy-rsmortgage-config-repository
          searchPaths: udemy-rsmortgage-customer-service,udemy-rsmortgage-customer-account-service
          username: dattabinit
          password: password123
eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://eureka-host1:8761/eureka/,http://eureka-host2:8762/eureka/
    fetchRegistry: true